version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: elyesmehri
      MYSQL_DATABASE: db
      MYSQL_USER: elyesmehri
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  springboot-app:
    image: elyesmehri/devopps:latest
    container_name: eventsProject
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db
      SPRING_DATASOURCE_USERNAME: elyesmehri
      SPRING_DATASOURCE_PASSWORD:
    ports:
      - "8080:8080"

volumes:
  mysql_data:
